### ISSUE TITLE
Elaborate on addressability

### ISSUE THREAD

**Issue by acln0** [romshark/Go-2-Proposal---Immutability#5]
For example, if `x` is a variable of type `const []T`, is `x[0]` addressable, as for regular slices? Justify the decision either way.

**Comment by romshark** [comment]
```go
x1 := const []T {T{}, T{}, T{}}
y1 := x1[0] // y1 is a mutable T

x2 := const [] const T {T{}, T{}, T{}}
y2 := x2[0] // y2 is an immutable T

x3 := const [] * const T {&T{}, &T{}, &T{}}
y3 := x3[0] // y3 is a pointer to an immutable T
```

I consider this issue resolved as it's already answered [by the FAQ section](https://github.com/romshark/Go-2-Proposal---Immutability#31-are-the-items-within-immutable-slicesmaps-also-immutable).
